services:
  gin-cicd-demo:
    image: crpi-jaurwvbawqqf7cfi.cn-beijing.personal.cr.aliyuncs.com/aimmetal/ci-cd-test:latest
    container_name: gin-cicd-demo
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      - GIN_MODE=release
